version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_af_installs
    description: "установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      
      - name: appsflyer_id
        description: "id установки"
        tests:
          - unique
          - not_null
  - name: llukyanchenko_af_installs
    description: "данные для дашборда"
    columns:
      - name: campaign_name
        description: "название кампании"
        tests:
          - not_null
      - name: adset_name
        description: "название объявления"
        tests:
          - not_null

        
      